#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui
